### ISSUE TITLE
Listing on Mailspring Community?

### ISSUE THREAD

**Issue by CodeMouse92** [faraadi/mailspring-nord-theme#2]
Mailspring just launched an official Discourse community which will house the catalog for themes and plugins, among other things. It would be great to have this theme listed there: https://community.getmailspring.com/c/themes/9

@faraadi and @SaeedBaig if you join, we can also add you to the Theme Designers group.

**Comment by SaeedBaig** [comment]
I'm happy for the theme to be listed and to join. What do I have to do?

**Comment by CodeMouse92** [comment]
@SaeedBaig Just go to https://community.getmailspring.com/ and sign up with your GitHub. Then, go to the Themes category and create a new topic.

You can request to be a member of the Theme Designers group here: https://community.getmailspring.com/g/theme_dev

**Comment by faraadi** [comment]
@CodeMouse92 Thanks for the details.
I'll make sure this theme will be listed in your community forum.
