### ISSUE TITLE
Unreadable text color in Outlook mails

### ISSUE THREAD

**Issue by axgkl** [faraadi/mailspring-nord-theme#3]
Hey, best theme, thanks.

Just had one problem: getting a lot of html email guess from outlook where the color is set to dark blue - unreadable in the preview pane in your theme:

![2021-03-09_1041x238_scrot](https://user-images.githubusercontent.com/9989548/110548967-a8c81e80-8131-11eb-9596-933464e1d007.png)

Checked what the built in ui-dark theme  does differently, there the blue is bright light blue.

Answer: they have a little extra stylesheet for that:

```js
styles$ cat email-frame.less
.ignore-in-parent-frame {
  body {
    filter: invert(100%) hue-rotate(180deg);
    color: #111;
  }
  img {
    filter: invert(100%) hue-rotate(180deg);
  }
}
```

with that:

![2021-03-09_906x207_scrot](https://user-images.githubusercontent.com/9989548/110549018-c0070c00-8131-11eb-999b-1008ed8edcda.png)

**Comment by faraadi** [comment]
Thanks, @AXGKl for the feedback.

I've tried many mails from different providers (including Outlook) and did not face this issue.

Can you send/forward [me](mailto:faradidev@gmail.com) the mail in screenshots or something like it?

**Comment by axgkl** [comment]
hi, sorry for delay, I forwarded an example to your gmail. Screenshot is also in the OP.  The additional .less file fixes it here (and as said, they have it also in their default dark theme, so I guess it's safe).

PS: 
> I've tried many mails from different providers (including Outlook) and did not face this issue.

Confirmed, appart from that issue the theme really looks polished on pretty much anything thrown at me ;-)

**Comment by axgkl** [comment]
closing - not relevant anymore.
